global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'sumax-erp-backend-tracking'
    scheme: https
    metrics_path: '/prod/sumax-erp-backend-tracking2/actuator/prometheus'
    static_configs:
      - targets: ['api-cluster-tracking.sumax.pe']
    scrape_interval: 5s
    scrape_timeout: 3s
    tls_config:
      insecure_skip_verify: true
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
