apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # URL de Prometheus en Render
    url: https://prometheus-tracking.onrender.com
    isDefault: true
    editable: true
